In [13]:
import numpy as np
import copy

In [12]:
v = np.zeros([5,5])
gamma = 0.9
print(v[0][0])

0.0


In [4]:
rA = 0; cA = 1;
rB = 0; cB = 3;

In [76]:
T = 1000 #stop after these many steps
noa = 4;

In [44]:
def getNewState(a):
    if a == 0:                      #UP
        s_next = [s[0]-1, s[1]]
    elif a == 1:                    #LEFT
        s_next = [s[0], s[1]-1]
    elif a == 2:                    #DOWN
        s_next = [s[0]+1, s[1]]
    else:                           #RIGHT
        s_next = [s[0], s[1] + 1]
        
    return s_next    

In [82]:
def getReward(a,s):
    s_next = getNewState(a)
    if s_next[0] < 0 or s_next[0] >= 5 or s_next[1] < 0 or s_next[1] >= 5:
        r = -1;       
    else:
        r = 0;
        
    return r;    

In [83]:
def getV(v,s,a):
    s_next = getNewState(a)
    if s_next[0] < 0 or s_next[0] >= 5 or s_next[1] < 0 or s_next[1] >= 5:
        v_s = v[s[0]][s[1]];
    else:
        v_s = v[s_next[0]][s_next[1]]
        
    return v_s    

In [84]:
s = [0,0]; #starting with this state
v = np.zeros([5,5])
steps = 0;
flag = 0;
th = 0.0001; #theshold for converging 
while flag == 0:    
    print("steps: " , steps)
    tmp = 0;
    #if in cell A with reward 10
    if s[0] == rA and s[1] == cA: 
        s_next = [4,1];
        tmp = 10 + gamma*v[s_next[0]][s_next[1]];
    #if in cell B with reward 5    
    elif s[0] == rB and s[1] == cB: 
        s_next = [2,3];
        tmp = 5 + gamma*v[s_next[0]][s_next[1]]; 
    #any other cell    
    else:
        for a in range(noa):    
            tmp += (getReward(a,s) + gamma*getV(v,s,a))*(1.0/noa)
            
    #chekcing for convergence        
    if abs(tmp - v[s[0]][s[1]]) < th:
        #STOP
        print("DONE")
        flag = 1;
        break;
    #update v if no convergence
    else:
        v[s[0]][s[1]] = tmp;
        
    #iterating over all the states    
    if s[0] == 4:
        s[0] = 0;
        if s[1] == 4:
            s[1] = 0;
        else:
            s[1] += 1;        
    else:
        s[0] += 1;
    
    print(v)
    print("")
        
    steps += 1;    

('steps: ', 0)
[[-0.5  0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0. ]]

('steps: ', 1)
[[-0.5     0.      0.      0.      0.    ]
 [-0.3625  0.      0.      0.      0.    ]
 [ 0.      0.      0.      0.      0.    ]
 [ 0.      0.      0.      0.      0.    ]
 [ 0.      0.      0.      0.      0.    ]]

('steps: ', 2)
[[-0.5        0.         0.         0.         0.       ]
 [-0.3625     0.         0.         0.         0.       ]
 [-0.3315625  0.         0.         0.         0.       ]
 [ 0.         0.         0.         0.         0.       ]
 [ 0.         0.         0.         0.         0.       ]]

('steps: ', 3)
[[-0.5         0.          0.          0.          0.        ]
 [-0.3625      0.          0.          0.          0.        ]
 [-0.3315625   0.          0.          0.          0.        ]
 [-0.32460156  0.          0.          0.          0.        ]
 [ 0.          0.          0.        

 [-1.81012954 -1.30313131 -1.18230975 -1.37771598 -1.93070191]]

('steps: ', 386)
[[ 3.36248678  8.83465931  4.47150191  5.3712265   1.54168569]
 [ 1.57100098  3.03591059  2.29086393  1.95393201  0.59326023]
 [ 0.0987228   0.78069307  0.72027296  0.40352992 -0.35848877]
 [-0.92601545 -0.39332129 -0.30794926 -0.54043095 -1.13862044]
 [-1.81012954 -1.30313131 -1.18230975 -1.37771598 -1.93070191]]

('steps: ', 387)
[[ 3.36248678  8.83465931  4.47150191  5.3712265   1.54168569]
 [ 1.57100098  3.03591059  2.29086393  1.95393201  0.59326023]
 [ 0.0987228   0.78069307  0.71260597  0.40352992 -0.35848877]
 [-0.92601545 -0.39332129 -0.30794926 -0.54043095 -1.13862044]
 [-1.81012954 -1.30313131 -1.18230975 -1.37771598 -1.93070191]]

('steps: ', 388)
[[ 3.36248678  8.83465931  4.47150191  5.3712265   1.54168569]
 [ 1.57100098  3.03591059  2.29086393  1.95393201  0.59326023]
 [ 0.0987228   0.78069307  0.71260597  0.40352992 -0.35848877]
 [-0.92601545 -0.39332129 -0.3157776  -0.54043095 -1.13862044

[[ 3.31842687  8.79678549  4.43487371  5.32898252  1.50050542]
 [ 1.53027647  2.99971987  2.25691219  1.91394297  0.55498237]
 [ 0.05912787  0.74535283  0.67962027  0.36553613 -0.3959571 ]
 [-0.96549335 -0.42847023 -0.34853077 -0.57844064 -1.17610154]
 [-1.84969146 -1.3382804  -1.22298646 -1.41583806 -1.9682957 ]]

('steps: ', 642)
[[ 3.31842687  8.79678549  4.43487371  5.32898252  1.50050542]
 [ 1.53027647  2.99971987  2.25691219  1.91394297  0.55498237]
 [ 0.05912787  0.74535283  0.67962027  0.36431224 -0.3959571 ]
 [-0.96549335 -0.42847023 -0.34853077 -0.57844064 -1.17610154]
 [-1.84969146 -1.3382804  -1.22298646 -1.41583806 -1.9682957 ]]

('steps: ', 643)
[[ 3.31842687  8.79678549  4.43487371  5.32898252  1.50050542]
 [ 1.53027647  2.99971987  2.25691219  1.91394297  0.55498237]
 [ 0.05912787  0.74535283  0.67962027  0.36431224 -0.3959571 ]
 [-0.96549335 -0.42847023 -0.34853077 -0.57963558 -1.17610154]
 [-1.84969146 -1.3382804  -1.22298646 -1.41583806 -1.9682957 ]]

('steps: ', 644

 [-1.85678369 -1.34443927 -1.22841443 -1.4221213  -1.9744068 ]]

('steps: ', 937)
[[ 3.31008051  8.79014631  4.4284419   5.32326207  1.49311619]
 [ 1.52258586  2.99316292  2.25090829  1.90843407  0.54825583]
 [ 0.05177511  0.73899014  0.67385115  0.35901498 -0.40233348]
 [-0.97266451 -0.43469452 -0.3540194  -0.58479818 -1.18229212]
 [-1.85678369 -1.34443927 -1.22841443 -1.4221213  -1.9744068 ]]

('steps: ', 938)
[[ 3.31008051  8.79014631  4.4284419   5.32326207  1.49311619]
 [ 1.52258586  2.99316292  2.25090829  1.90843407  0.54825583]
 [ 0.05177511  0.73899014  0.67385115  0.35901498 -0.40233348]
 [-0.97266451 -0.43469452 -0.35416259 -0.58479818 -1.18229212]
 [-1.85678369 -1.34443927 -1.22841443 -1.4221213  -1.9744068 ]]

('steps: ', 939)
[[ 3.31008051  8.79014631  4.4284419   5.32326207  1.49311619]
 [ 1.52258586  2.99316292  2.25090829  1.90843407  0.54825583]
 [ 0.05177511  0.73899014  0.67385115  0.35901498 -0.40233348]
 [-0.97266451 -0.43469452 -0.35416259 -0.58479818 -1.18229212

In [85]:
print(v)

[[ 3.30975112  8.78988648  4.4281915   5.32298959  1.49283049]
 [ 1.52228266  2.99290595  2.25067445  1.90817139  0.54799585]
 [ 0.0514856   0.73874091  0.67362657  0.35876254 -0.4025796 ]
 [-0.97294649 -0.43493809 -0.35428202 -0.58504396 -1.18253071]
 [-1.85706236 -1.34468013 -1.228674   -1.42236402 -1.97464213]]
